### ISSUE TITLE
[FEATURE] Icon font based css 

### ISSUE THREAD

**Issue by coding46** [jhpoelen/taxaprisma#2]
If there is a way to obtain the icons in svg or another vector format we could create an icon font.

Given this we could build a nice css file which defines the icons and its color:
(f.x.)
```css
.fungi-icon {
    font-family: Taxaprisma-Icon-Font;
}
.fungi-icon:before {
    content: "\e034"; // code for the icon in the font
}
.fungi-icon-colored {
    color: #f52887;
}
```

Would be really easy to get those icons to work without image handling and stuff.
